#pragma once

// Settings Dialog
#define IDD_SETTINGS 101

// Tab Control
#define IDC_TAB_SETTINGS 1001

// Tab Pages
#define IDD_TAB_APPEARANCE 102
#define IDD_TAB_MARKDOWN 103
#define IDD_TAB_TAGS 104

// Appearance Tab Controls
#define IDC_RADIO_THEME_LIGHT 1101
#define IDC_RADIO_THEME_DARK 1102
#define IDC_RADIO_THEME_SYSTEM 1103
#define IDC_COMBO_FONT_FACE 1104
#define IDC_COMBO_FONT_SIZE 1105
#define IDC_CHECK_CLICKABLE_LINKS 1106
#define IDC_CHECK_CLICKABLE_EMAILS 1107

// Markdown Tab Controls
#define IDC_CHECK_USE_MARKDOWN 1201
#define IDC_CHECK_SHOW_FORMAT_MENU 1202
#define IDC_CHECK_RENDER_ON_OPEN 1203
#define IDC_CHECK_DOUBLE_CLICK_EDIT 1204
#define IDC_CHECK_DOUBLE_CLICK_MARKDOWN 1205

// Tags Tab Controls
#define IDC_LIST_TAGS 2001
#define IDC_EDIT_TAG 2002
#define IDC_BUTTON_ADD_EDIT_TAG 2003
#define IDC_BUTTON_DELETE_TAG 2004
#define IDC_BUTTON_UP_TAG 2005
#define IDC_BUTTON_DOWN_TAG 2006

// Toolbar
#define IDM_SETTINGS 3001
#define IDI_SETTINGS 4001
